config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  # User Management
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations:      'users/registrations' }
  resources :identities, only: :destroy, param: :provider

  namespace :admin do
    get '/' => 'dashboard#index', as: :dashboard

    # Users
    resources :users do
      member { post 'reset_password' }
    end
  end
end

app/views/shared/_admin_nav.html.erb
<li>
  <%= link_to 'Dashboard', admin_dashboard_path %>
</li>
<li class="<%= active_for_subnav(:users) %>">
  <%= link_to 'Users', admin_users_path %>
</li>

app/views/shared/_alert.html.erb
<%# Alert control from Bootstrap framework for public pages %>
<div class="alert alert-<%= css_class %> alert-dismissable" role="alert">
  <div class="container">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <div class="alert-message"><%= sanitize(message).html_safe %></div>
  </div>
</div>

app/views/shared/_analytics.html.erb
<script id="google-analytics">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-61424797-1', 'auto');
  ga('require', 'ecommerce');
  ga('send', 'pageview');
</script>

<% if Rails.env.production? %>
  <script type="text/javascript">
  window.addEventListener('load',function(){
    var timer = setInterval(function(){
      var $response = $('.response');
      if($response.is(":visible")){
        ga('send','event','Form','Submit','Get it Now');
        var conversion = 'www.googleadservices.com/pagead/conversion/925597418/?label=XjosCOz7tWYQ6v2tuQM&guid=ON&script=0';
        $('body').append('<img height="1" width="1" style="border-style:none;" alt="" src="//' + conversion + '"/>');
        clearInterval(timer);

        if ($response.text().indexOf('Welcome to') >= 0) {
          setTimeout(function(){ window.location = '/?utm_source=google&utm_medium=adwords&utm_campaign=join-us-optin'; }, 500);
        }
      }
    },1000);

    jQuery('.track-booking').click(function(){
      var conversionId;

      switch (campType) {
      case 'east':
        conversionId = 'W64fCJHhhGgQ6v2tuQM';
        ga('send','event','Button','Click','East');
        break;

      case 'west':
        conversionId = 'Lu3CCKPhhGgQ6v2tuQM';
        ga('send','event','Button','Click','West');
        break;

      default:
        conversionId = 'a07yCJ_JtGcQ6v2tuQM';
        ga('send','event','Button','Click','Book ticket');
        break;
      }

      var conversion = 'www.googleadservices.com/pagead/conversion/925597418/?label=' + conversionId + '&guid=ON&script=0';
      $('body').append('<img height="1" width="1" style="border-style:none;" alt="" src="//' + conversion + '"/>');
    });

    jQuery('.optin-btn').click(function(){
      ga('send','event','Button','Click','Optin');
      var conversion = 'www.googleadservices.com/pagead/conversion/925597418/?label=LiziCITjhGgQ6v2tuQM&guid=ON&script=0';
      $('body').append('<img height="1" width="1" style="border-style:none;" alt="" src="//' + conversion + '"/>');
    });
  })
  </script>
<% end %>

app/views/shared/_facebook.html.erb
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');

fbq('init', '421155831388202');
fbq('track', "PageView");</script>
<noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=421155831388202&ev=PageView&noscript=1"
  /></noscript>
<!-- End Facebook Pixel Code -->

app/views/shared/_flash_messages.html.erb
<section class="flash-messages">
  <%= flash_message page_specific: :page_specific_notice, flash: notice, css_class: :info   %>
  <%= flash_message page_specific: :page_specific_alert,  flash: alert,  css_class: :danger %>
  <%= devise_error_messages %>
</section>

app/views/shared/_footer.html.erb
<footer class="container-fluid">
  <div class="background"></div>
  <div class="copyright">COPYRIGHT &copy; 2017 Satilife. All rights reserved.</div>
</footer>

app/views/shared/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle pull-left" data-toggle="collapse" data-target="#header-nav" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

      <ul class="nav pull-right">
        <li class="pull-left">
          <% if admin? %>
            <%= link_to ENV['SITE_NAME'], root_path, class: 'nav-link' %>
          <% else %>
            <p class="navbar-btn">
              <%#= link_to 'BOOK YOUR TICKET NOW', bookings_path, class: 'track-booking btn btn-primary-alt btn-xs' %>
            </p>
          <% end %>
        </li>

        <%= render 'shared/user_profile' %>
      </ul>
    </div>

    <nav id="header-nav" class="collapse navbar-collapse navbar-left">
      <ul class="nav navbar-nav">
        <% if admin? %>
          <%= render 'shared/admin_nav' %>
        <% elsif user_signed_in? %>
          <%= render 'shared/user_nav' %>
        <% else %>
          <%= render 'shared/site_nav' %>
        <% end %>
      </ul>
    </nav>
  </div>

  <hr>
</header>

<div id="header-spacer"></div>

app/views/shared/_meta_tags.html.erb
<%= csrf_meta_tags %>

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<meta name="description" content="Patricia Moreno">
<meta name="robots" content="noodp,noydir">

app/views/shared/_page_header.html.erb
<title>
  Patricia Moreno<%= " #{content_for(:title)}" if content_for?(:title) %>
</title>

<%= render 'shared/meta_tags' %>

<link rel="canonical" href="//soul.camp/">
<link rel="icon" href="/favicon.ico" type="image/x-icon">

app/views/shared/_record_errors.html.erb
<% if record.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_site_nav.html.erb
<li class="<%= hide_for('welcome') %>">
  <%= link_to root_path do %>
    <%= fa_icon 'home' %>
  <% end %>
</li>
<li>
  <%#= link_to 'Soul Camp Creative', creative_index_path %>
</li>

app/views/shared/_subnav.html.erb
<!--nav class="row">
  <ul class="nav nav-pills">
    <li class="<%= active_for('registrations') %>">
      <%= link_to 'My Account', edit_user_registration_path %></li>
    </li>
  </ul>
  <hr>
</nav-->

app/views/shared/_user_nav.html.erb
<li class="<%= hide_for('welcome') %>">
  <%= link_to root_path do %>
    <%= fa_icon 'home' %>
  <% end %>
</li>
<li class="<%= active_for_subnav(:account) %>">
  <%= link_to 'My Account', edit_user_registration_path %></li>
</li>

app/views/shared/_user_profile.html.erb
<% if user_signed_in? %>
  <li id="user-profile" class="dropdown pull-right">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
      <% if current_user.photo? %>
        <%= image_tag current_user.photo, width: 25 %>
      <% else %>
        <%= fa_icon 'user' %>
      <% end %>
      <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <% if current_user.admin? %>
        <li><%= link_to 'Admin', admin_dashboard_path %></li>
      <% end %>
      <li><%= link_to 'My Account', edit_user_registration_path %></li>
      <li role="separator" class="divider"></li>
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
    </ul>
  </li>
<% else %>
  <li id="user-profile" class="pull-right">
    <%= link_to new_user_session_path, class: 'login' do %>
      <%= fa_icon 'user' %>
      <strong class="hidden-xs hidden-sm">Sign In</strong>
    <% end %>
  </li>
<% end %>