config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  # User Management
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations:      'users/registrations' }
  resources :identities, only: :destroy, param: :provider

  namespace :admin do
    get '/' => 'dashboard#index', as: :dashboard

    # Users
    resources :users do
      member { post 'reset_password' }
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  first_name             :string           not null
#  last_name              :string           not null
#  email                  :string           not null
#  phone_number           :string
#  birthdate              :date
#  admin                  :boolean          default(FALSE)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  password_set           :boolean          default(TRUE)
#  avatar                 :string
#  uploaded_avatar        :string
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_first_name            (first_name)
#  index_users_on_last_name             (last_name)
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  include Authenticatable
  include Avatarable

  mount_uploader :uploaded_avatar, AvatarUploader

  auto_strip_attributes :first_name, :last_name, :email

  before_save :titleize_name
  before_save :downcase_email

  has_many :identities,   dependent: :destroy

  validates_presence_of :first_name, :last_name

  scope :ordered,         -> { order(:first_name, :last_name) }
  scope :admin,           -> { where(admin: true) }
  scope :standard,        -> { where(admin: false) }

  scope :for_review,      -> { eager_load(:identities) }
  scope :for_listing,     -> { for_review.ordered }

  def self.search(search)
    where('first_name ILIKE :search OR last_name ILIKE :search OR email ILIKE :search', search: "%#{search.strip}%")
  end

  def name
    "#{first_name} #{last_name}"
  end

  def initials
    "#{first_name.chr}#{last_name.chr}"
  end

  def abbr_name
    "#{first_name} #{last_name.chr}."
  end

  def password_required?
    return false unless password_set?
    super
  end

  def photo
    return uploaded_avatar.url if uploaded_avatar.present?
    avatar
  end

  def photo?
    uploaded_avatar.present? || avatar.present?
  end

  private

  def downcase_email
    self.email = email.downcase
  end

  def titleize_name
    self.first_name = first_name.titleize
    self.last_name  = last_name.titleize
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::CrudController
  def reset_password
    send_password_reset
    redirect_to :back
  end

  private

  def subnav
    :users
  end

  def records_scope
    :for_listing
  end

  def deletable?
    !@record.admin?
  end

  def build_address
    @record.build_address unless @record.address.present?
  end

  def update_record_with_valid_params
    @record.update_without_password(valid_params) && @record.valid?
  end

  def handle_success
    send_password_reset if params.fetch(:user, {}).key?(:send_password_email)
    super
  end

  def send_password_reset
    @record.send_reset_password_instructions
    flash[:notice] = 'Password reset email has been sent!'
  end

  def valid_params
    params.require(:user).permit(allowed_parameters)
  end

  def allowed_parameters
    [ :first_name,
      :last_name,
      :email,
      :admin,
      :password,
      :password_set,
      :uploaded_avatar ]
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_action :redirect_on_oauth_error,
                :add_identity_to_existing_user,
                :set_user_from_identity

  def facebook
    authenticate_user_from 'Facebook'
  end

  def google_oauth2
    authenticate_user_from 'Google'
  end

  private

  def authenticate_user_from(provider)
    if user_signed_in?
      redirect_to edit_user_registration_path(current_user)
    else
      sign_in_and_redirect @user, event: :authentication
    end
    set_flash_message(:notice, :success, kind: provider) if is_navigational_format?
  end

  def redirect_on_oauth_error
    return unless request.env.key?('omniauth.error')
    logger.error request.env['omniauth.error']
    handle_error(generic_error_message)
  end

  def generic_error_message
    'Sorry, your request could not be completed due to an error.'
  end

  def auth
    request.env['omniauth.auth']
  end

  def add_identity_to_existing_user
    return unless user_signed_in?
    current_user.add_omniauth(auth)
  end

  def set_user_from_identity
    return if user_signed_in?

    @user = User.from_omniauth(auth)
    @user.save! unless @user.persisted?
  rescue => error
    handle_error(error.message)
  end

  def handle_error(message)
    flash.alert = message
    redirect_to new_user_session_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  before_action :set_registration_presenter,
                                            only: [:edit, :update]

  protected

  def after_update_path_for(resource)
    edit_registration_path(resource)
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(*allowed_parameters) }
  end

  def allowed_parameters
    [ :first_name,
      :last_name,
      :email,
      :current_password,
      :password,
      :password_confirmation ]
  end

  def update_resource(resource, params)
    if params[:password].blank?
      resource.update_without_password(params)
    elsif resource.password_set?
      resource.update_with_password(params)
    else
      resource.update_with_first_password(params)
    end
  rescue StandardError => e
    flash[:alert] = 'There was an error with your request.'
    Rails.logger.error(e.message)
  end

  def current_user
    @current_user ||= super && User.for_review.find(@current_user.id)
  end

  def set_registration_presenter
    @presenter = RegistrationsPresenter.new(current_user, view_context)
  end
end

app/views/admin/users/_authentication.html.erb
<table class="table table-headless">
  <tbody>
    <tr class="<%= 'danger' if @record.sign_in_count.zero? %>">
      <th>Sign In Count</th>
      <td><%= @record.sign_in_count %></td>
    </tr>
    <% unless @record.sign_in_count.zero? %>
      <tr>
        <th>Current Sign In</th>
        <td><%= format_datetime(@record.current_sign_in_at) %></td>
      </tr>
      <tr>
        <th>Current Signed In From</th>
        <td><%= @record.current_sign_in_ip %></td>
      </tr>
      <tr>
        <th>Last Signed In</th>
        <td><%= format_datetime(@record.last_sign_in_at) %></td>
      </tr>
      <tr>
        <th>Last Signed In From</th>
        <td><%= @record.last_sign_in_ip %></td>
      </tr>
    <% end %>
    <tr>
      <th>Password Set?</th>
      <td><%= yes_no_label(@record.password_set?) %></td>
    </tr>
    <tr>
      <th>Reset Password</th>
      <td>
        <%= link_to 'Send Password Reset', reset_password_admin_user_path(@record), method: :post, class: 'btn btn-xs' %>
      </td>
    </tr>
  </tbody>
</table>

<% if @record.identities.length > 0 %>
  <hr>
  <table class="table">
    <thead>
      <tr>
        <th>Provider</th>
        <th>UID</th>
      </tr>
    </thead>
    <tbody>
      <% @record.identities.each do |identity| %>
        <tr>
          <td><%= identity.label %></td>
          <td><%= identity.uid %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/admin/users/_form.html.erb
<%= simple_form_for [:admin, @record], html: { multipart: true } do |f| %>
  <%= f.input :password_set, as: :hidden, input_html: { value: false } %>
  <%= f.input :password,     as: :hidden, input_html: { value: Devise.friendly_token[0,20] } %>

  <div class="row">
    <div class="col-xs-6">
      <%= f.input :first_name %>
    </div>
    <div class="col-xs-6">
      <%= f.input :last_name %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <%= f.input :email, required: true %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <%= f.input :admin %>
    </div>
  </div>

  <% if newish? %>
    <div class="row">
      <div class="col-xs-12">
        <%= f.input :send_password_email, as: :boolean, input_html: { checked: false } %>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-xs-12">
      <%= f.input :uploaded_avatar, as: :file %>
    </div>
  </div>

  <% if @record.photo? %>
    <div class="row">
      <div class="col-xs-12">
        <%= image_tag @record.photo, width: 144 %>
      </div>
    </div>
  <% end %>

  <hr>

  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/admin/users/_index.html.erb
<h2>Find Users</h2>
<div class="row">
  <div class="col-xs-12 col-md-3">
    <%= form_tag('/admin/users', method: :get) do %>
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search" name="search" value="<%= params[:search] %>">
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <i class="glyphicon glyphicon-search"></i>
          </button>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-xs-12 col-md-6">
  </div>
</div>

<h2>User List</h2>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <% @records.each do |record| %>
        <tr>
          <td><%= link_to record.name, admin_user_path(record) %></td>
          <td><%= mail_to record.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/users/_info.html.erb
<% if @record.photo? %>
<div class="col-xs-2 text-center">
  <%= image_tag @record.photo, width: 72 %>
</div>
<div class="col-xs-10">
<% else %>
<div class="col-xs-12">
<% end %>
  <table class="table table-headless">
    <tbody>
      <tr>
        <th>Name</th>
        <td><%= @record.name %></td>
      </tr>
      <tr>
        <th>Email</th>
        <td><%= mail_to @record.email %></td>
      </tr>
      <tr>
        <th>Admin</th>
        <td><%= yes_no_label @record.admin? %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/admin/users/_show.html.erb
<div class="row">
  <div class="col-xs-12 col-md-7">
    <div class="panel panel-default panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= fa_icon 'user' %>
          User Info
        </h3>
      </div>
      <div class="panel-body">
        <%= render 'info' %>
      </div>
    </div>
  </div>

  <div class="col-xs-12 col-md-5">
    <div class="panel panel-default panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%= fa_icon 'unlock-alt' %>
          Authentication Info
        </h3>
      </div>
      <div class="panel-body">
        <%= render 'authentication' %>
      </div>
    </div>
  </div>
</div>